name: Build libsbml

on:
  push:
  release:
    types: [created]
    
jobs:

  build_linux:
    strategy:
      matrix:
        os: [
          {image: ubuntu-22.04, glibc: "2.35"}, 
          {image: ubuntu-24.04, glibc: "2.39"}
        ]
      fail-fast: false
    runs-on: ${{ matrix.os.image }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile libSBML dependencies
      run: |
        git clone --recurse-submodules https://github.com/sbmlteam/libSBML-dependencies.git
        cd libSBML-dependencies
        cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DWITH_LIBXML=ON \
          -DWITH_ZLIB=ON \
          -DWITH_ICONV=ON \
          -DWITH_BZIP2=ON \
          -DWITH_CHECK=OFF \
          -DLIBXML2_WITH_ZLIB=ON
        cmake --build build --parallel 4
        sudo cmake --install build
    
    - name: Compile libSBML
      run: |
        wget https://github.com/sbmlteam/libsbml/archive/refs/tags/v5.20.5.tar.gz
        tar -zxf v5.20.5.tar.gz
        cd libsbml-5.20.5
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/lib/x86_64-linux-gnu/libxml2.a \
        -DLIBXML_INCLUDE_DIR=/usr/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        -DWITH_CPP_NAMESPACE=ON \
        -DBUILD_SHARED_LIBS=OFF \
        ..
        make -j 4
        sudo make install
        cd ..
        mkdir package
        cd package
        mkdir lib
        cp /usr/lib/libsbml-static.a /usr/lib/libzlib.a /usr/lib/libbz2.a /usr/lib/x86_64-linux-gnu/libxml2.a lib/
        
        mkdir include
        cp -r /usr/include/sbml/ include/
        tar -zcvf ../libSBML-5.20.5-linux64-glibc${{ matrix.os.glibc }}.tar.gz *

    - uses: actions/upload-artifact@v4
      with:
        name: libSBML-5.20.5-linux64-glibc${{ matrix.os.glibc }}
        path: ${{ github.workspace }}/libsbml-5.20.5/package/*
          
      
    - uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: libSBML-5.20.5-linux64-glibc${{ matrix.os.glibc }}.tar.gz
        asset_path: ${{ github.workspace }}/libsbml-5.20.5/libSBML-5.20.5-linux64-glibc${{ matrix.os.glibc }}.tar.gz
        asset_content_type: application/gzip

  build_macosx:
    strategy:
      matrix:
        os: [
          {image: macos-13, gcc: "12", macosx_deployment_target: "13.0", name: osx-x86_64}, 
          {image: macos-14, gcc: "13", macosx_deployment_target: "14.0", name: osx-14-arm64}, 
          {image: macos-15, gcc: "15", macosx_deployment_target: "15.0", name: osx-15-arm64}
        ]
      fail-fast: false
    runs-on: ${{ matrix.os.image }}
    env:
      CC: gcc-${{ matrix.os.gcc }}
      CXX: g++-${{ matrix.os.gcc }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os.macosx_deployment_target }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      if: ${{ matrix.os.name == 'osx-15-arm64' }}
      run : |
        brew uninstall gcc
        brew install gcc
    
    - name: Compile libSBML dependencies
      run: |
        git clone --recurse-submodules https://github.com/sbmlteam/libSBML-dependencies.git
        cd libSBML-dependencies
        cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local/ \
          -DWITH_LIBXML=ON \
          -DWITH_ZLIB=ON \
          -DWITH_ICONV=ON \
          -DWITH_BZIP2=ON \
          -DWITH_CHECK=OFF \
          -DLIBXML2_WITH_ZLIB=ON
        cmake --build build --parallel 4
        sudo cmake --install build
          
    - name: Compile libSBML
      run: |
        wget https://github.com/sbmlteam/libsbml/archive/refs/tags/v5.20.5.tar.gz
        tar -zxf v5.20.5.tar.gz
        cd libsbml-5.20.5
        
        if [[ "${{ matrix.os.name }}" == "osx-15-arm64" ]]; then
            #Hacky fix for gcc 15
            sed -i '10i #include <cstdint>' ./src/sbml/html2md/html2md.h
        fi
        
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ \
        -DCMAKE_INSTALL_LIBDIR=/usr/local/lib/ \
        -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
        -DWITH_SWIG=OFF \
        -DLIBXML_LIBRARY=/usr/local/lib/libxml2.a \
        -DLIBXML_INCLUDE_DIR=/usr/local/include/libxml2 \
        -DENABLE_COMP=ON \
        -DENABLE_FBC=ON \
        -DENABLE_GROUPS=ON \
        -DENABLE_LAYOUT=ON \
        -DENABLE_MULTI=ON \
        -DENABLE_QUAL=ON \
        -DENABLE_RENDER=ON \
        -DENABLE_DISTRIB=ON \
        -DWITH_CPP_NAMESPACE=ON \
        -DBUILD_SHARED_LIBS=OFF \
        ..
        make -j 4
        sudo make install
        cd ..
        mkdir package
        cd package
        mkdir lib
        cp /usr/local/lib/libsbml-static.a /usr/local/lib/libzlib.a /usr/local/lib/libbz2.a /usr/local/lib/libxml2.a lib/
        mkdir include
        cp -r /usr/local/include/sbml include/
        tar -zcvf ../libSBML-5.20.5-${{ matrix.os.name }}.tar.gz *

    - uses: actions/upload-artifact@v4
      with:
        name: libSBML-5.20.5-${{ matrix.os.name }}
        path: ${{ github.workspace }}/libsbml-5.20.5/package/*

    - uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: libSBML-5.20.5-${{ matrix.os.name }}.tar.gz
        asset_path: ${{ github.workspace }}/libsbml-5.20.5/libSBML-5.20.5-${{ matrix.os.name }}.tar.gz
        asset_content_type: application/gzip   
                  
  build_windows:
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: flex bison make git mingw-w64-x86_64-binutils mingw-w64-x86_64-gcc mingw-w64-x86_64-headers-git mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-python mingw-w64-x86_64-python-zstandard mingw-w64-x86_64-python-cffi make bison flex mingw-w64-x86_64-ca-certificates mingw-w64-x86_64-diffutils mingw-w64-x86_64-python-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-lapack mingw-w64-x86_64-openblas mingw-w64-x86_64-cmake mingw-w64-x86_64-tools-git
    
    - name: Compile libSBML dependencies
      run: |
        git clone --recurse-submodules https://github.com/sbmlteam/libSBML-dependencies.git
        cd libSBML-dependencies
        cmake -G"MSYS Makefiles" -B build -S . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_INSTALL_PREFIX=/mingw64 \
          -DWITH_LIBXML=ON \
          -DWITH_ZLIB=ON \
          -DWITH_ICONV=ON \
          -DWITH_BZIP2=ON \
          -DWITH_CHECK=OFF \
          -DLIBXML2_WITH_ZLIB=ON
        cmake --build build --parallel 4 -v
        cmake --install build
    
        
    - name: Compiling libSBML
      run: |
        wget https://github.com/sbmlteam/libsbml/archive/refs/tags/v5.20.5.tar.gz
        tar -zxf v5.20.5.tar.gz
        cd libsbml-5.20.5
        
        #Hacky fix for gcc 15
        sed -i '10i #include <cstdint>' ./src/sbml/html2md/html2md.h

        mkdir build
        cd build        
        
        cmake  -G"MSYS Makefiles" \
          -DCMAKE_INSTALL_PREFIX=/mingw64/ \
          -DCMAKE_INSTALL_LIBDIR=/mingw64/lib \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_STANDARD_LIBRARIES=-lxml2 \
          -DWITH_SWIG=OFF \
          -DLIBXML_LIBRARY=/mingw64/lib/libxml2.a \
          -DLIBXML_INCLUDE_DIR=/mingw64/include/libxml2 \
          -DENABLE_COMP=ON \
          -DENABLE_FBC=ON \
          -DENABLE_GROUPS=ON \
          -DENABLE_LAYOUT=ON \
          -DENABLE_MULTI=ON \
          -DENABLE_QUAL=ON \
          -DENABLE_RENDER=ON \
          -DENABLE_DISTRIB=ON \
          -DBUILD_SHARED_LIBS=OFF \
          ..
        make VERBOSE=1 -j 4
        make install
        cd ..
        mkdir package
        cd package
        mkdir lib
        cp /mingw64/lib/libsbml-static.a /mingw64/lib/liblibbz2.a /mingw64/lib/libzdll.a /mingw64/lib/libxml2.a lib/
        mkdir include
        cp -r /mingw64/include/sbml/ include/
        tar -zcvf ../libSBML-5.20.5-win64-${{ matrix.os }}.tar.gz *

    - uses: actions/upload-artifact@v4
      with:
        name: libSBML-5.20.5-win64-${{ matrix.os }}
        path: ${{ github.workspace }}\libsbml-5.20.5\package\*
        
    - uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: libSBML-5.20.5-win64-${{ matrix.os }}.tar.gz
        asset_path: ${{ github.workspace }}\libsbml-5.20.5\libSBML-5.20.5-win64-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip